apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: guestbook
    tier: backend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 5000
    # targetPort: 9999
  selector:
    app: guestbook
    tier: backend