apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend-dpl
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # only allow at most one pod unavailable for work
      maxUnavailable: 1
      # can have no more than one extra pod
      maxSurge: 1
  template:
    metadata:
      labels:
        app: guestbook
        tier: backend
    spec:
      containers:
      - name: python
        image: lyudmila/python-redis-backend:v1.0
        # env:
        # - name: GET_HOSTS_FROM
          # value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 5000
