apiVersion: v1
kind: Service
metadata:
  name: redis-slave-svc
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  type: NodePort 
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30162
  selector:
    app: redis
    role: slave
    tier: backend
